'use client'
import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillLinkedin, AiFillGithub } from 'react-icons/ai'
import { useState } from 'react'
import Image from 'next/image'

export default function Home() {
  const [darkMode, setDarkMode] = useState(true)

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Matheus Orozimbo Portifólio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white dark:bg-slate-800 px-10 md:px-20 lg:px-40'>
        <section className=" min-h-screen">
            <nav className='py-10 mb-12 flex justify-between'>
              <h1 className='text-xl font-burtons dark:text-white md:text-2xl lg:text-3xl'>DevelopedByOrozimbo1</h1>
              <ul className='flex items-center'>
                <li>
                  <BsFillMoonStarsFill className='cursor-pointer text-2xl md:text-4xl dark:text-white' onClick={() => setDarkMode(!darkMode)} />
                </li>
                <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 md:text-2xl' href="#">Resume</a></li>
              </ul>
            </nav>
            <div className='text-center p-10'>
              <h2 className='text-2xl py-2 text-teal-500 font-medium md:text-4xl lg:text-6xl'>Matheus Orozimbo</h2>
              <h3 className='text-1xl py-2 md:text-2xl lg:text-4xl dark:text-white'>Desenvolvedor Full Stack</h3>
              <p className='text-md py-5 leading-7 text-gray-500 md:text-xl lg:text-2xl dark:text-white'>
                Algumacoisasobremimalgum acoisasobremimalguma  coisa sobremimalgumacoisasobr emimalgumacois asobremimalgumacoisaso bremimalgumacoisasobremim
              </p>
            </div>
            <div className='text-4xl flex justify-center gap-10 py-3 text-gray-600 dark:text-white md:text-5xl lg:text-6xl'>
              <AiFillLinkedin />
              <AiFillGithub />
            </div>
            <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-72 h-72 my-10 overflow-hidden md:h-96 md:w-96'>
              {/* <Image src={dev} layout="fill" objectFit="cover" /> */}
            </div>
        </section>
        <section>
          <div>
            <h3 className='text-2xl py-1 md:text-3xl lg:text-5xl dark:text-white'>Serviços que presto</h3>
            <p className='text-md leading-7 py-2 md:text-xl lg:text-2xl dark:text-white'>
              Um texto descrevendo o que eu sei fazer
              Um texto descrevendo o que eu sei fazer
              Um texto descrevendo o que eu sei fazer
              Um texto descrevendo o que eu sei fazer
              Um texto descrevendo o que eu sei fazer
              Um texto descrevendo o que eu sei fazer
            </p>
            <div className='md:flex gap-10 justify-center flex-wrap'>
              <div className='text-center shadow-lg p-5 my-5 dark:bg-white'>
                {/* <Image src={imagemdoqueeufaço} layout="fill" objectFit="cover" /> */}
                <div className='mx-auto h-40 w-40 rounded-md my-10 md:h-52 md:w-52 lg:h-60 lg:w-60 bg-teal-500'></div>
                <h3 className='text-lg font-medium pt-8 pb-2 md:text-2xl lg:text-3xl'>
                  Titulo de uma area que faço
                </h3>
                <p className='text-md leading-7 py-2 md:text-xl lg:text-2xl'>
                  Um texto descrevendo essa área
                </p>
                <h4 className='py-4 text-teal-600 md:text-2xl lg:text-3xl'>
                  Ferramentas que uso nessa área
                </h4>
                <p className='text-gray-800 py-1 md:text-xl lg:text-2xl'>ferramenta</p>
                <p className='text-gray-800 py-1 md:text-xl lg:text-2xl'>ferramen</p>
                <p className='text-gray-800 py-1 md:text-xl lg:text-2xl'>ferra</p>
                <p className='text-gray-800 py-1 md:text-xl lg:text-2xl'>fe</p>
                <p className='text-gray-800 py-1 md:text-xl lg:text-2xl'>f</p>
              </div>
              <div className='text-center shadow-lg p-5 my-5 dark:bg-white'>
                {/* <Image src={imagemdoqueeufaço} layout="fill" objectFit="cover" /> */}
                <div className='mx-auto h-40 w-40 bg-teal-500 rounded-md my-10 md:h-52 md:w-52 lg:h-60 lg:w-60 '></div>
                <h3 className='text-lg font-medium pt-8 pb-2 md:text-2xl lg:text-3xl '>
                  Titulo de uma area que faço
                </h3>
                <p className='text-md leading-7 py-2 md:text-xl lg:text-2xl'>
                  Um texto descrevendo essa área
                </p>
                <h4 className='py-4 text-teal-600 md:text-2xl lg:text-3xl'>
                  Ferramentas que uso nessa área
                </h4>
                <p className='text-gray-800 py-1 md:text-xl lg:text-2xl'>ferramenta</p>
                <p className='text-gray-800 py-1 md:text-xl lg:text-2xl'>ferramen</p>
                <p className='text-gray-800 py-1 md:text-xl lg:text-2xl'>ferra</p>
                <p className='text-gray-800 py-1 md:text-xl lg:text-2xl'>fe</p>
                <p className='text-gray-800 py-1 md:text-xl lg:text-2xl'>f</p>
              </div>
              <div className='text-center shadow-lg p-5 my-5 dark:bg-white'>
                {/* <Image src={imagemdoqueeufaço} layout="fill" objectFit="cover" /> */}
                <div className='mx-auto h-40 w-40 bg-teal-500 rounded-md my-10 md:h-52 md:w-52 lg:h-60 lg:w-60 '></div>
                <h3 className='text-lg font-medium pt-8 pb-2 md:text-2xl lg:text-3xl'>
                  Titulo de uma area que faço
                </h3>
                <p className='text-md leading-7 py-2 md:text-xl lg:text-2xl'>
                  Um texto descrevendo essa área
                </p>
                <h4 className='py-4 text-teal-600 md:text-2xl lg:text-3xl'>
                  Ferramentas que uso nessa área
                </h4>
                <p className='text-gray-800 py-1 md:text-xl lg:text-2xl'>ferramenta</p>
                <p className='text-gray-800 py-1 md:text-xl lg:text-2xl'>ferramen</p>
                <p className='text-gray-800 py-1 md:text-xl lg:text-2xl'>ferra</p>
                <p className='text-gray-800 py-1 md:text-xl lg:text-2xl'>fe</p>
                <p className='text-gray-800 py-1 md:text-xl lg:text-2xl'>f</p>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-2xl py-1 md:text-3xl dark:text-white'>Portfolio</h3>
            <p className='text-md leading-7 py-2 md:text-xl lg:text-2xl dark:text-white'>
              Um texto descrevendo o que e meu portfolio
              Um texto descrevendo o que e meu portfolio
              Um texto descrevendo o que e meu portfolio
              Um texto descrevendo o que e meu portfolio
              Um texto descrevendo o que e meu portfolio
              Um texto descrevendo o que e meu portfolio
            </p>
          </div>
          <div className='flex flex-col items-center gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-3/12 flex-1'>
              {/* <Image src={Imagemdosmeuprojetos} className='rounded-sm object-cover bg-teal-500' width={'100%'} heigth={'100%'} layout="responsive"/> */}
              <div className='rounded-sm object-cover bg-teal-500 w-80 h-80 '></div>
            </div>
            <div className='basis-3/12 flex-1'>
              {/* <Image src={Imagemdosmeuprojetos} className='rounded-sm object-cover bg-teal-500' width={'100%'} heigth={'100%'} layout="responsive"/> */}
              <div className='rounded-sm object-cover bg-teal-500 w-80 h-80 '></div>
            </div>
            <div className='basis-3/12 flex-1'>
              {/* <Image src={Imagemdosmeuprojetos} className='rounded-sm object-cover bg-teal-500' width={'100%'} heigth={'100%'} layout="responsive"/> */}
              <div className='rounded-sm object-cover bg-teal-500 w-80 h-80 '></div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
